FF01/Models/Forum/ForumIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FF01.Models.Forum
{
    public class ForumIndexModel
    {
        public IEnumerable<ForumListingModel> ForumList { get; set; }

    }
}

FF01/Models/Forum/ForumListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FF01.Models.Forum
{
    public class ForumListingModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }


    }
}

FF01/Models/Forum/ForumTopicModel.cs
using FF01.Models.Post;
using System.Collections.Generic;

namespace FF01.Models.Forum
{
    public class ForumTopicModel
    {
        public ForumListingModel Forum { get; set; }
        public IEnumerable<PostListingModel> Posts { get; set; }
    }
}

FF01/Controllers/ForumController.cs
using FF01.Data;
using FF01.Data.Models;
using FF01.Models.Forum;
using FF01.Models.Post;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace FF01.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;


        public ForumController(IForum forumService)
        {
            _forumService = forumService;
        }
        public IActionResult Index()
        {
            //IEnumerable<ForumListingModel> forums = _forumService.GetAll();
            var forums = _forumService.GetAll()
                .Select(forum => new ForumListingModel {
                    Id = forum.Id,
                    Name = forum.Title,
                    Description = forum.Description
                });

            var model = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(model);
        }

        public IActionResult Topic(int id)
        {
            var forum = _forumService.GetByID(id);
            //var posts = _postService.GetPostsByForum(id); REFACTORING 
            var posts = forum.Posts;

            var postListings = posts.Select(p => new PostListingModel
            {
                Id = p.Id,
                AuthorId = p.User.Id,
                AuthorRating = p.User.Rating,
                Title = p.Title,
                DatePoster = p.Created,
                RepliesCount = p.Replies.Count(),
                Forum = BuildForumListing(p)
            });

            var model = new ForumTopicModel
            {
                Posts = postListings,
                Forum = BuildForumListing(forum)
            };

            return View(model) ;
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {          
            return new ForumListingModel
            {
                Id = forum.Id,
                Name = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }
        private ForumListingModel BuildForumListing(Post p)
        {
            var forum = p.Forum;

           return BuildForumListing(p);
        }
    }
}

FF01/Controllers/PostController.cs
using FF01.Data;
using FF01.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FF01.Controllers
{
    public class PostController : Controller
    {
        private readonly IPost _postService;
        public PostController(IPost postService)
        {
            _postService = postService;
        }

        public IActionResult Index(int id)
        {
            var post = _postService.GetByID(id);

            var replies = BuildPostReplies(post.Replies);

            var model = new PostIndexModel
            {
                Id = post.Id,
                Title = post.Title,
                AuthorId = post.User.Id,
                AuthorName = post.User.UserName,
                AuthorImageUrl = post.User.ProfilImangeUrl,
                AuthorRating = post.User.Rating,
                Created = post.Created,
                PostContent = post.Content,
                Replies = replies

            };

            return View(model);
        }

        private IEnumerable<PostReplyModel> BuildPostReplies(IEnumerable<PostReply> replies)
        {
            return replies.Select(r => new PostReplyModel
            {
                Id = r.Id,
                AutherName = r.User.UserName,
                AuthorId = r.User.Id,
                AuthorImageUrl = r.User.ProfilImangeUrl,
                AuthorRating = r.User.Rating,
                ReplyContent = r.Content
            });
        }
    }
}

FF01/Views/Forum/Index.cshtml
@model FF01.Models.Forum.ForumIndexModel


<h1>Forums</h1>
<table class="table table-hover" id="forumIndexTable">
    <tbody>
        @foreach (var forum in Model.ForumList)
        {
            <tr>
                <td>
                    <a asp-controller="Forum" asp-action="Topic" asp-route-id="@forum.Id">
                        @forum.Name
                    </a>
                </td>
                
                <td>@forum.Description</td>
            </tr>
        }
    </tbody>
</table>

FF01/Views/Forum/Topic.cshtml
@model FF01.Models.Forum.ForumTopicModel

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
@if (Model.Posts.Any())
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th></th>
            </tr>
        </thead>

        <tbody>

            @foreach (var item in Model.Posts)
            {
                <tr>
                    <td>
                        <a asp-controller="Post" asp-action="Index" asp-route-id="@item.Id">
                            @item.Title
                        </a>                           
                    </td>
                    <td>
                        @item.AuthorName
                    </td>
                    <td>
                        @item.DatePoster
                    </td>
                    <td>
                        @item.RepliesCount
                    </td>
                </tr>
            }


        </tbody>

    </table>
 }

else {
     <div class="notPosts">
        <h3>
            No Items in the @Model.Forum.Name yet

            <a asp-controller="Post" asp-action="Create" asp-route-id="@Model.Forum.Id">
                <span>Create</span>
            </a>
        </h3>
     </div>
}